// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20211121133330_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Categories");
            });

            modelBuilder.Entity("WebApi.Models.Customer", b =>
            {
                b.Property<string>("Email")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("nvarchar(80)");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("ZipCode")
                    .IsRequired()
                    .HasColumnType("char(5)");

                b.HasKey("Email");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Customers");
            });

            modelBuilder.Entity("WebApi.Models.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("CategoryNameId")
                    .HasColumnType("int");

                b.Property<string>("LongDescription")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(200)");

                b.Property<decimal>("Price")
                    .HasColumnType("money");

                b.Property<string>("ShortDescription")
                    .IsRequired()
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.HasIndex("CategoryNameId");

                b.ToTable("Products");
            });

            modelBuilder.Entity("WebApi.Models.Product", b =>
            {
                b.HasOne("WebApi.Models.Category", "CategoryName")
                    .WithMany("Products")
                    .HasForeignKey("CategoryNameId");

                b.Navigation("CategoryName");
            });

            modelBuilder.Entity("WebApi.Models.Category", b =>
            {
                b.Navigation("Products");
            });
#pragma warning restore 612, 618
        }
    }
}